destination: _site/
url: "http://127.0.0.1:4005"
baseurl: "/labs-pdf"
port: 4005
output: pdf
product: labs
print_title: CPSC 220 Labs
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true
